server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non-null
  datasource:
    url: jdbc:mysql://localhost:3306/pagination
    username: root
    password: root
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
